### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by a-shkarlatov** [jhswartz/ipconfigstore#2]
Hi @jhswartz , could you help? I get an error when I do /configure.ac

```
./configure.ac: line 1: syntax error near unexpected token `[ipconfigstore],'
./configure.ac: line 1: `AC_INIT([ipconfigstore], [0.1], [bugs@risingedge.co.za])'
```

What am I doing wrong?

**Comment by jhswartz** [comment]
Which platform are you building on? And which versions of autotools have you got?

**Comment by jhswartz** [comment]
Feel free to reopen this issue if you aren't sorted.

**Comment by a-shkarlatov** [comment]
ty very much, now it works
