### ISSUE TITLE
ipconfigstore on windows/WSL

### ISSUE THREAD

**Issue by nathanveach** [jhswartz/ipconfigstore#3]
Hello sorry I'm pretty new to Linux / Android - I usually just use the WSL cli on windows for those applications.  I've tried cloning this repo and running make, but can't seem to get it working.  Do you think this is just a compatibility issue?  Below is a sample of commands I've tried, but keep getting 'command not found.'

![image](https://github.com/user-attachments/assets/817a5bc5-bd60-4d96-bedd-6dbd9a9e4141)

**Comment by jhswartz** [comment]
Prefix `ipconfigstore` with `./`, so that you have `./ipconfigstore`. This prefix tells the shell to look for the ipconfigstore executable in the current working directory.

**Comment by jhswartz** [comment]
I've never considered using ipconfigstore on Windows, so I'm keen to hear how it pans out for you.

**Comment by nathanveach** [comment]
Ah that worked perfectly! Thank you so much!
